package com.pixelmc.pixellogic.core.model;

public enum NodeType {
    MANUAL_TRIGGER,
    COMMAND_TRIGGER,
    STATE_COMPARE_CONDITION,
    MESSAGE_ACTION,
    PLAYER_HAS_TAG_CONDITION,
    PLAYER_IS_ADMIN_CONDITION,
    PLAYER_DIMENSION_CONDITION,
    PLAYER_IN_REGION_CONDITION,
    PLAYER_Y_COMPARE_CONDITION,
    TARGET_BLOCK_TYPE_CONDITION,
    TARGET_BLOCK_IN_REGION_CONDITION,
    TARGET_BLOCK_Y_COMPARE_CONDITION,
    PLAYER_NEAR_TARGET_BLOCK_CONDITION,
    PLAYER_ADD_TAG_ACTION,
    PLAYER_REMOVE_TAG_ACTION,
    CONTROL_LOOP_COUNT,
    CONTROL_LOOP_FOREVER,
    CONTROL_LOOP_UNTIL,
    STATE_SET_ACTION,
    STATE_ADD_ACTION,
    TIMER_START_ACTION,
    DEBUG_LOG_ACTION
}
