pluginManagement {
	repositories {
		maven {
			name = 'Aliyun Gradle Plugin'
			url = 'https://maven.aliyun.com/repository/gradle-plugin'
		}
		maven {
			name = 'Aliyun Public'
			url = 'https://maven.aliyun.com/repository/public'
		}
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		gradlePluginPortal()
		mavenCentral()
	}
}

rootProject.name = 'pixel-logic'
