export const dragThreshold = 6;
export const doubleClickMs = 340;
export const autoSaveDelayMs = 650;
export const historyLimit = 80;
export { normalBlockHeight, normalBlockWidth, puzzleConnectedOverlap as connectedOverlap, puzzleMouthHalfHeight } from '../../model/containerGeometry';
export const conditionBlockWidth = 384;
export const conditionBranchGap = 104;
export const insertSnapX = 188;
export const insertSnapY = 118;
export const linkSnapX = 64;
export const linkSnapY = 42;
export const reconnectSnapX = 24;
export const reconnectSnapY = 18;
export const visualConnectXTolerance = 8;
export const visualConnectYTolerance = 6;
